data_config:
  dataset_name: "CIFAR10"
  IID: false
  alpha: 10
  global_batch_size: 64
  std_client_samples: 0
---
model_config:
  net: "LeNet5_MOD"
  criterion: "torch.nn.CrossEntropyLoss"
  optimizer: "torch.optim.SGD"
---
optim_config:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0004
---
fed_config:
  num_clients: 50
  avg_clients_rounds: 0.75
  std_clients_rounds: 0
  num_rounds: 15
  client_batch_size: 64 
  local_epochs: 1
  fed_IR: false
  fed_VC: false

