data_config:
  dataset_name: "CIFAR10"
  IID: False
  alpha: 5
  global_batch_size: 64
  std_client_samples: 0.2
---
model_config:
  net: "LeNet5_MOD_LIGHT"
  criterion: "torch.nn.CrossEntropyLoss"
  optimizer: "torch.optim.SGD"
---
optim_config:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0004
---
fed_config:
  num_clients: 6
  avg_clients_rounds: 1 
  std_clients_rounds: 0
  num_rounds: 4
  client_batch_size: 64 
  local_epochs: 3

  fed_IR: True
  fed_VC: True